version: '3'
services:
  steamspy-mysql:
    image: mysql:8.0.33
    container_name: steamspy-mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    # SQL이 켜진 다음 collector 수집 체크
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$MYSQL_ROOT_USER", "-p$MYSQL_ROOT_PASSWORD", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  steamspy-collector:
    build:
      context: .
      dockerfile: dockerfile
    container_name: steamspy-collector
    depends_on:
      steamspy-mysql:
        condition: service_healthy
    command: ["steamspy-mysql"]

networks:
  default:
    name: steamspy-network