FROM amd64/python:3.9.16-bullseye

RUN apt-get update && \
    apt-get install -y default-mysql-client && \
    rm -rf var/lib/apt/lists/*

WORKDIR /app

COPY . . 

RUN pip install -U pip && \
    pip install --no-cache-dir -r requirements.txt 

RUN chmod +x ./container_collect_data.py

# ENTRYPOINT ["python", "./container_collect_data.py", "--db-host"]

# CMD 

# CMD ["steamspy-mysql"]