FROM amd64/python:3.9.16-bullseye

RUN apt-get update && \
    rm -rf var/lib/apt/lists/*

WORKDIR /app

COPY . . 

RUN pip install -U pip && \
    pip install --no-cache-dir -r requirements.txt 

# 컨테이너 실행 시 시작되는 프로세스
ENTRYPOINT ["python", "container_collect_data.py", "--db-host"]

CMD ["localhost"]